version: '3'

services:
    mongo2:
        image: mongo:4.0.0-xenial
        command: -replSet rs0
        container_name: mongo_primary
        ports:
            - "27017:27017"
        restart: always
#        volumes:
#            - /home/ubuntu/lyuye/mongodb/db:/data/db/